# Generated by Django 5.0.6 on 2025-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
