version: '3'
services:
  afisha:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8001:8000'
    depends_on:
      - postgresdb

  postgresdb:
    image: 'postgres:12'
    hostname: postgresdb
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test_database
    ports:
      - '5433:5432'
    volumes:
      - distributor-postgres:/var/lib/postgresql/data
volumes:
  distributor-postgres:

